baseURL = 'https://trail.guegan.cloud'
languageCode = 'fr'
DefaultContentLanguage = 'fr'
title = 'Mes aventures en courses à pied'
theme = 'hugo-paper'

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'
distance = 'distances'
denivele = 'deniveles'
temps = 'temps'
type = 'types'
ville = 'villes'
strava_id = 'strava_ids'

[menu]
  [[menu.main]]
    identifier = 'resultats'
    name = 'Résultats'
    url = '/resultats'
    weight = 10
  [[menu.main]]
    identifier = 'carte'
    name = 'Carte'
    url = '/carte/'
    weight = 10
  [[menu.main]]
    identifier = 'stats'
    name = 'Stats'
    url = '/stats/'
    weight = 10

[params]
  color = 'linen'
  strava = 'athletes/97656573'
  avatar = 'iguegankergal@hotmail.fr'
  name = 'Gael GUEGAN'
  bio = 'La douleur est éphémère, la fierté est éternelle ...'
  monoDarkIcon = true
